#!/bin/bash

if [[ $# != 3 ]] ; then
    echo 'ERROR: Bad arguments'
    echo 'USAGE: repl_server <ADDR> <SESSION> <OUTPUT_DIR>'
    echo 'Argument ADDR: the address on which this sever listens, e.g., "127.0.0.1:6666"'
    echo "Argument SESSION: an Isabelle session. Only theories within this session can be loaded by this shell. set this to 'HOL' if you have no idea and we strongly refer you to Isabelle's system reference, chapter 2 <Isabelle sessions and build management>."
    echo 'Argument OUTPUT_DIR: the directory used to store all the files generated by the Isabelle theories evaluated by this shell. The path must be given in POSIX format, in which only the forward-slash "a/b/c" is valid but the backslash "a\b\c" is invalid.'
    echo 'Example: repl_server 127.0.0.1:6666 HOL /tmp/repl_outputs'
    exit 1
fi

echo "Hi, this is Isabelle REPL Server."
echo "When you see \"Running REPL$$ ...\", it means I am successfully lanched and listening on $1."

DIR=$(mktemp -d)
echo "theory REPL$$ imports \"Isa_REPL.Isa_REPL\" begin ML \\<open>Isabelle_Thread.join (REPL_Server.startup (Path.explode \"$(printf '%b' $3)\") NONE \"$(printf '%b' $1)\"); error \"IGNORE THIS ERROR\"\\<close> end" > $DIR/REPL$$.thy
echo "session REPL$$ = \"$(printf '%b' $2)\" + sessions Isa_REPL theories REPL$$" > $DIR/ROOT
isabelle build -D $DIR REPL$$

#isabelle process -l $2 -f $base/contrib/mlmsgpack/mlmsgpack-aux.sml -f $base/contrib/mlmsgpack/realprinter-packreal.sml -f $base/contrib/mlmsgpack/mlmsgpack.sml -f $base/library/REPL.ML -f $base/library/REPL_serializer.ML -f $base/library/Server.ML -e "REPL_Server.startup ${(qqq)3} NONE ${(qqq)1}"

