/*  Title:      src/scala/repl_tool.scala
    Author:     Qiyuan Xu

The `isabelle REPL` tool: start the Isa-REPL server on a logic session,
replacing repl_server.sh (plan 二).  Runs in the JVM that `isabelle` starts;
models tat.scala (Theory-Agent-over-Trees).  No ML source here: the load
command lives in library/repl_boot.ML, the startup command in the tail of
library/Server.ML.
*/

package isabelle.isa_repl

import isabelle._

import scala.collection.mutable


object REPL_Tool {

  /* the events the ML side and the process report; the first ending wins */

  sealed abstract class Outcome
  case object Loaded extends Outcome
  case class Ready(addr: String) extends Outcome
  case class Failed(text: String) extends Outcome
  case class Ended(rc: Int, why: String) extends Outcome

  /* isabelle.Session is abstract; session_options must be a def/constructor val,
     not a class-body val -- the super constructor computes Store(session_options)
     before a class-body val is assigned (session.scala:148) */

  class Boot_Session(process_options: Options, session_resources: Resources)
    extends Session {
    override def session_options: Options = process_options
    override val resources: Resources = session_resources
  }

  val boot: Path = Path.explode("$ISA_REPL_HOME/library/repl_boot.ML")

  val isabelle_tool: Isabelle_Tool =
    Isabelle_Tool("REPL", "start the Isa-REPL server on a logic session",
      Scala_Project.here,
      { args =>
        // 1a. first action: mark ourselves (and all we fork/exec) OOM-preferred
        try { File.write(Path.explode("/proc/self/oom_score_adj"), "1000") }
        catch { case _: Throwable => }

        val dirs = new mutable.ListBuffer[Path]
        var logic = Isabelle_System.default_logic()
        var qualifier: Option[String] = None
        val user_specs = new mutable.ListBuffer[Options.Spec]
        var wait_timeout = Time.seconds(600)
        var log_file: Option[Path] = None
        var mute = true

        val getopts = Getopts("""
Usage: isabelle REPL [OPTIONS] ADDR OUTPUT_DIR

  Options are:
    -l NAME      logic session (default: ISABELLE_LOGIC=""" + quote(logic) + """)
    -q NAME      default theory qualifier for client connections (default: LOGIC)
    -d DIR       as Isabelle's -d: a further session-root directory
    -o OPTION    as Isabelle's -o: override an Isabelle system option
    -T SECONDS   time to wait for load and for startup (default: 600)
    -L FILE      log every prover message to FILE
    -V           do not mute the server's own output

  Start the Isa-REPL server: build the logic session's heap if needed, start
  an ML process with a Scala peer on it, load Isa_REPL, then serve on ADDR,
  storing files generated by evaluated theories under OUTPUT_DIR.
""",
          "L:" -> (arg => log_file = Some(Path.explode(arg))),
          "T:" -> (arg => wait_timeout = Time.seconds(Value.Double.parse(arg))),
          "V" -> (_ => mute = false),
          "d:" -> (arg => dirs += Path.explode(arg)),
          "l:" -> (arg => logic = arg),
          "o:" -> (arg => user_specs += Options.Spec.make(arg)),
          "q:" -> (arg => qualifier = Some(arg)))

        val (addr, output_dir) =
          getopts(args) match {
            case List(a, d) => (a, d)
            case _ => getopts.usage()
          }
        val qualifier_value = qualifier getOrElse logic

        // the launch line, before building options (repl_server.sh:80-83 prints
        // one too, so a run is identifiable in the log before any build)
        Output.writeln(
          "Isa-REPL on " + quote(logic) + " at " + addr + ", output in " + quote(output_dir),
          stdout = true)

        val dirs_list = dirs.toList
        val specs = user_specs.toList

        // two option sets, today's order, bound lexically apart (§4.1): build_options
        // lives only inside the block that produces background/heaps, so the tool's
        // content options cannot flow into the shared logic heap, and passing
        // process_options to Build.build_logic is a compile error, not a review note.
        val (background, heaps) = {
          val build_options =
            Options.init(specs = Options.Spec.ISABELLE_BUILD_OPTIONS) ++ specs
          val progress = new Console_Progress(stderr = true)
          progress.interrupt_handler {
            Build.build_logic(build_options, logic, dirs = dirs_list, progress = progress,
              build_heap = true, strict = true)
          }
          val bg = Sessions.background(build_options, logic, dirs = dirs_list).check_errors
          val hp = Store(build_options).session_heaps(bg, logic = logic)
          (bg, hp)
        }

        val process_options = {
          val base =
            ((Options.init(specs = Options.Spec.ISABELLE_BUILD_OPTIONS) + "quick_and_dirty=true")
              ++ specs) + "completion_limit=0" + "editor_tracing_messages=0"
          if (Isabelle_System.getenv("ISABELLE_RPC_HOME").nonEmpty)
            base + "isabelle_rpc_dialogue=absent"
          else base
        }

        val session = new Boot_Session(process_options, new Resources(background))

        val loaded = Synchronized[Option[Outcome]](None)
        val ready = Synchronized[Option[Outcome]](None)
        val ending = Synchronized[Option[Outcome]](None)
        def fill(slot: Synchronized[Option[Outcome]], outcome: Outcome): Unit =
          slot.change(_ orElse Some(outcome))
        def fill_all(outcome: Ended): Unit =
          { fill(loaded, outcome); fill(ready, outcome); fill(ending, outcome) }
        def fill_startup(outcome: Outcome): Unit =
          { fill(loaded, outcome); fill(ready, outcome) }

        session.init_protocol_handler(new Session.Protocol_Handler {
          override val functions: Session.Protocol_Functions =
            List(
              "Isa_REPL.loaded" -> ((_: Prover.Protocol_Output) =>
                { fill(loaded, Loaded); true }),
              "Isa_REPL.ready" -> ((_: Prover.Protocol_Output) =>
                { fill(ready, Ready(addr)); true }),
              "Isa_REPL.failed" -> ((msg: Prover.Protocol_Output) => {
                val text =
                  Pretty.string_of(Symbol.decode_yxml_failsafe(msg.text),
                    metric = Symbol.Metric, pure = true)
                Output.error_message(text)
                fill_startup(Failed(text))
                true
              }),
              "Isa_REPL.stopped" -> ((_: Prover.Protocol_Output) => {
                fill_all(Ended(Process_Result.RC.error,
                  "Isa-REPL accept thread exited on " + addr))
                true
              }))
        })

        // the process ending before it answers is an ending too
        session.phase_changed +=
          Session.Consumer[Session.Phase]("Isa_REPL") {
            case Session.Terminated(result) =>
              fill_all(Ended(result.rc, "Isabelle process terminated: " + result.print_rc))
            case _ =>
          }

        // stderr: every syslog-class prover message, unconditionally
        session.syslog_messages +=
          Session.Consumer[Prover.Output]("Isa_REPL.syslog") { output =>
            Output.writeln(XML.content(output.message))
          }
        // -L FILE: every prover message, one File.append each (no held writer)
        log_file.foreach { file =>
          session.all_messages +=
            Session.Consumer[Prover.Message]("Isa_REPL.log") {
              case output: Prover.Output => File.append(file, XML.content(output.message) + "\n")
              case _ =>
            }
        }

        val process =
          Isabelle_Process.start(process_options, session, background, heaps,
            use_prelude = List(File.platform_path(boot)),
            eval_main = Command_Line.ML_tool(List("Isabelle_Process.init_build ()")),
            cwd = File.path(Isabelle_System.tmp_dir("isa_repl")),
            env = Isabelle_System.Settings.env(putenv = List(
              "REPL_DEFAULT_SESSION" -> qualifier_value,
              "REPL_PID" -> ProcessHandle.current().pid().toString)))

        process.await_startup()

        def wait_for(slot: Synchronized[Option[Outcome]], what: String): Outcome = {
          val deadline = Time.now() + wait_timeout
          def loop(): Outcome =
            slot.timed_access(_ => Some(deadline), st => st.map(o => (o, st))) match {
              case Some(outcome) => outcome
              case None =>
                if (Time.now() < deadline) loop()
                else {
                  // the timeout is discovered here, so it is reported here (§4.3)
                  Output.error_message("Isa-REPL: timed out after " +
                    wait_timeout.seconds.toLong + "s waiting for " + what)
                  Failed("timed out waiting for " + what)
                }
            }
          loop()
        }

        def bail(outcome: Outcome): Nothing = {
          outcome match {
            case Failed(_) =>            // already written: the handler, or wait_for's timeout
            case Ended(_, why) => Output.error_message(why)
            case _ => Output.error_message("Isa-REPL startup failed")
          }
          session.stop()
          sys.exit(Process_Result.RC.error)
        }

        // 8. load Isa_REPL
        session.protocol_command("Isa_REPL.load")
        wait_for(loaded, "load") match {
          case Loaded =>
          case other => bail(other)
        }

        // 9. start the server
        session.protocol_command("Isa_REPL.startup",
          XML.string(addr), XML.string(output_dir), XML.string(if (mute) "true" else "false"))
        wait_for(ready, "startup") match {
          case Ready(_) =>
          case other => bail(other)
        }

        // 10. ready; then wait, without limit, for the first ending
        Output.writeln("Isa-REPL server ready at " + addr, stdout = true)
        ending.guarded_access(st => st.map(o => (o, st))) match {
          case Ended(rc, why) =>
            Output.error_message(why)
            session.stop()
            sys.exit(rc)
          case _ =>            // fill_startup never touches `ending`
            session.stop()
            sys.exit(Process_Result.RC.error)
        }
      })
}

class Tools extends Isabelle_Scala_Tools(REPL_Tool.isabelle_tool)
